CATEGORY_KEYWORDS = {
    "Billing": [
        "bill",
        "billing",
        "charge",
        "charged",
        "payment",
        "invoice",
        "subscription",
        "refund",
        "overcharged",
        "credit card",
        "debit",
        "transaction",
        "price",
        "pricing",
        "fee",
        "fees",
        "cost",
        "plan",
        "upgrade",
        "downgrade",
        "cancel",
        "cancellation",
        "receipt",
        "discount",
        "promo",
        "coupon",
        "renewal",
        "expired",
    ],
    "Technical": [
        "bug",
        "error",
        "crash",
        "not working",
        "broken",
        "issue",
        "glitch",
        "fail",
        "failed",
        "failure",
        "exception",
        "stack trace",
        "500",
        "404",
        "timeout",
        "slow",
        "performance",
        "loading",
        "login",
        "logout",
        "api",
        "endpoint",
        "integration",
        "server",
        "database",
        "connection",
        "network",
        "ssl",
        "cert",
        "deploy",
        "installation",
        "install",
        "update",
        "upgrade",
        "version",
        "patch",
    ],
    "Account": [
        "account",
        "profile",
        "password",
        "username",
        "email",
        "login",
        "sign in",
        "sign up",
        "register",
        "registration",
        "verify",
        "verification",
        "2fa",
        "two-factor",
        "locked",
        "suspended",
        "banned",
        "access",
        "permission",
        "role",
        "admin",
        "user",
        "settings",
        "preferences",
        "delete account",
        "close account",
        "change email",
        "reset",
    ],
    "Feature Request": [
        "feature",
        "request",
        "suggestion",
        "idea",
        "enhancement",
        "improve",
        "improvement",
        "add",
        "would be nice",
        "wish",
        "want",
        "need",
        "please add",
        "could you add",
        "roadmap",
        "future",
        "new feature",
        "functionality",
        "capability",
        "option",
        "toggle",
        "support for",
        "integrate",
        "integration with",
    ],
    "Security": [
        "security",
        "breach",
        "hack",
        "hacked",
        "phishing",
        "malware",
        "virus",
        "ransomware",
        "vulnerability",
        "exploit",
        "unauthorized",
        "suspicious",
        "fraud",
        "identity theft",
        "scam",
        "compromised",
        "leak",
        "data leak",
        "stolen",
        "intrusion",
        "attack",
        "ddos",
        "xss",
        "sql injection",
        "csrf",
        "authentication bypass",
        "token",
        "exposed",
        "sensitive data",
    ],
}

URGENCY_KEYWORDS = [
    "urgent",
    "urgently",
    "asap",
    "immediately",
    "emergency",
    "critical",
    "down",
    "outage",
    "not working",
    "broken",
    "production down",
    "prod down",
    "data loss",
    "lost data",
    "cannot access",
    "can't access",
    "locked out",
    "blocked",
    "stopping",
    "halting",
    "impact",
    "deadline",
    "right now",
    "today",
    "hours",
    "minutes",
    "sla",
    "breach",
    "major issue",
]

PRIORITY_BOOST_SIGNALS = {
    "P0": [
        "production down",
        "prod down",
        "outage",
        "data loss",
        "lost data",
        "system down",
        "complete failure",
        "critical failure",
        "breach",
        "security breach",
        "hacked",
        "unauthorized access",
        "ransomware",
    ],
    "P1": [
        "urgent",
        "asap",
        "immediately",
        "emergency",
        "cannot access",
        "blocked",
        "major bug",
        "major issue",
        "high priority",
        "business impact",
    ],
    "P2": [
        "slow",
        "performance",
        "degraded",
        "intermittent",
        "sometimes fails",
        "workaround",
        "workaround exists",
    ],
    "P3": [
        "suggestion",
        "would be nice",
        "minor",
        "when possible",
        "no rush",
        "low priority",
        "idea",
        "nice to have",
    ],
}

CATEGORY_TIEBREAKER_ORDER = [
    "Security",
    "Billing",
    "Technical",
    "Account",
    "Feature Request",
    "Other",
]
